name: Playwright Automated Testing Framework

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser

      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./.github/scripts/InstallChrome.sh
          ./.github/scripts/InstallChrome.sh

      - name: Test
        run: mvn clean test -Ptest